name: SimpleWebApp
env:
  APPLICATION_NAME : "SimpleWebApp"

on: [push]

jobs:
  run-tests:

    runs-on: [ubuntu-18.04]

    steps:
      - name: Java version
        run: java -version

      - name: Installing maven
        run: sudo apt-get -y install maven

      - name: Maven version
        run: mvn -version

      - name: Clone repository
        uses: actions/checkout@v1

      - name: Run tests
        run: mvn test

  run-build:
    needs: run-tests
    runs-on: [ ubuntu-18.04 ]

    steps:
      - name: Java version
        run: java -version

      - name: Installing maven
        run: sudo apt-get -y install maven

      - name: Maven version
        run: mvn -version

      - name: Clone repository
        uses: actions/checkout@v1

      - name: Run build
        run: mvn package

  build-and-publish:
    needs: run-build
    runs-on: [ ubuntu-18.04 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Run ls -l
        run: ls -l

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/simple-web-app:latest
